### ISSUE TITLE
add support for windows

### ISSUE THREAD

**Issue by softprops** [softprops/screenprints#1]
I'm pretty sure [this](https://github.com/softprops/screenprints/blob/bd8cdc8ea31581790de6010047734b0e2ca1ac7a/src/lib.rs#L73-L74) isn't going to work for windows. We can probably do a conditional compile with and automate a test with [appveyor](https://ci.appveyor.com)

**Comment by nabijaczleweli** [comment]
I'll try and have a crack at this, if I may
